# Generated by Django 4.1.7 on 2023-02-22 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_create', models.DateField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_favirutes', to='entrada.entry')),
            ],
            options={
                'verbose_name': 'Entrada favorita',
                'verbose_name_plural': 'Entradas favoritas',
            },
        ),
    ]
