# Generated by Django 4.1.7 on 2023-02-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254)),
                ('messagge', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_create', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.TextField()),
                ('about_title', models.CharField(max_length=50, verbose_name='Titulo Nosotros')),
                ('about_text', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('phone', models.CharField(max_length=20, verbose_name='telefono de contacto')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_create', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pagina Principal',
                'verbose_name_plural': 'pagina Principal',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_create', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'suscripctor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
    ]
